import type { Metadata, Viewport } from 'next';

import { Analytics } from '@vercel/analytics/next';
import { ThemeProvider } from 'next-themes';
import { LayoutProvider } from '@/components/layout/layout-provider';
import { DataLoaderProvider } from '@/components/providers/data-loader-provider';
import { MotionProvider } from '@/components/providers/motion-provider';
import { SessionProvider } from '@/components/providers/session-provider';
import { TRPCProvider } from '@/components/providers/trpc-provider';
import { WalletProvider } from '@/components/wallet/wallet-context';
import './animations.css';
import './globals.css';



export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Draw under notches; `pb-safe` / env(safe-area-inset-*) keep content clear.
  viewportFit: 'cover',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#6166f1' },
    { media: '(prefers-color-scheme: dark)', color: '#a78bfa' },
  ],
  colorScheme: 'light dark',
};

export const metadata: Metadata = {
  title: {
    default: 'Tamgora — Discover Top Creative Talent',
    template: '%s — Tamgora',
  },
  description:
    'Discover, hire, and collaborate with exceptional creators across design, writing, marketing, product management, and 10+ more disciplines. Post bounties, find freelancers, and build amazing projects.',
  keywords: [
    'creators',
    'portfolio',
    'bounty',
    'design',
    'writing',
    'content creation',
    'freelance',
    'showcase',
    'stellar',
  ],
  generator: 'v0.app',
  openGraph: {
    title: 'Tamgora — Discover Top Creative Talent',
    description:
      'Discover, hire, and collaborate with exceptional creators across design, writing, marketing, product management, and 10+ more disciplines.',
    type: 'website',
    siteName: 'Tamgora',
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Tamgora — Discover Top Creative Talent',
    description:
      'Discover, hire, and collaborate with exceptional creators across design, writing, marketing, product management, and 10+ more disciplines.',
  },
  robots: { index: true, follow: true },
  icons: {
    icon: {
      url: '/icon.svg',
      type: 'image/svg+xml',
    },
    // apple-touch-icon and the PNG favicon fallback are generated by
    // app/apple-icon.tsx and app/icon.tsx (Next.js file-convention icons),
    // auto-discovered — no entry needed here.
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body className="font-sans antialiased transition-smooth">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <SessionProvider>
            <WalletProvider>
              <TRPCProvider>
                <DataLoaderProvider>
                  <MotionProvider>
                    <LayoutProvider>{children}</LayoutProvider>
                  </MotionProvider>
                </DataLoaderProvider>
              </TRPCProvider>
            </WalletProvider>
          </SessionProvider>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
